### ISSUE TITLE
Statistics

### ISSUE THREAD

**Issue by danlindb** [gmonterovillar/HAMON#2]
Interesting idea for improvement in HAMON:

1. Store a vector that contains a counter of the number of feasible and unfeasible individuals for each generation, so that one can see how much of the population that was actually satisfying the constraints in the simulation. This can be a good indicator to whether you have too tight constraints or simply initialise the population with really bad initial values, yielding a large amount of unsatisfactory individuals.
2. Include plots functions of above functionality in the end of each HAMON run.

**Comment by gmonterovillar** [comment]
Implemented
